### ISSUE TITLE
Last commit 304519f not buildable

### ISSUE THREAD

**Issue by HenriWahl** [schachr/docker-snorby#3]
Hi,
your latest commit https://github.com/schachr/docker-snorby/commit/304519f1f28147e4199eb3535d9233803864f857 results in an unbuildable image:

Downloading https://github.com/rvm/rvm/archive/1.29.7.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.7/1.29.7.tar.gz.asc
gpg: Signature made Thu Jan  3 22:01:48 2019 UTC using RSA key ID 39499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/usr/local/rvm/archives/rvm-1.29.7.tgz'
Creating group 'rvm'
Installing RVM to /usr/local/rvm/
Installation of RVM in /usr/local/rvm/ is almost complete:

  * First you need to add all users that will be using rvm to 'rvm' group,
    and logout - login again, anyone using rvm will be operating with `umask u=rwx,g=rwx,o=rx`.

  * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
    in all your open shell windows, in rare cases you need to reopen all shell windows.
  * Please do NOT forget to add your users to the <code>rvm</code> group.
     The installer no longer auto-adds root or users to the rvm group. Admins must do this.
     Also, please note that group memberships are ONLY evaluated at login time.
     This means that users must log out then back in before group membership takes effect!
  * WARNING:  version This account is currently not available. detected - Zsh 4.3.12 / 5.0.0+ is recommended,
     with current one errors to be expected - bugs in shell code interpretation.
/bin/sh: bundle: command not found
/bin/sh: bundle: command not found
/bin/sh: bundle: command not found
The command '/bin/sh -c yum clean all &&     yum update -y &&     yum install -y epel-release &&     yum install -y tar wget git libxml2-devel libxslt-devel mariadb mariadb-devel postgresql-devel wkhtmltopdf &&     yum clean all &&     curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - &&     curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import - &&     curl --silent -L "https://raw.githubusercontent.com/rvm/rvm/stable/binscripts/rvm-installer" | bash -s stable --ruby=1.9.3 &&     source /usr/local/rvm/scripts/rvm &&     source /etc/profile.d/rvm.sh &&     export PATH=$PATH:/usr/local/rvm/rubies/ruby-1.9.3-p551/bin &&     gem update --system &&     yum install -y https://snort.org/downloads/snort/daq-2.0.6-1.centos7.x86_64.rpm &&     yum install -y https://snort.org/downloads/snort/snort-2.9.12-1.centos7.x86_64.rpm &&     wget -O /tmp/community-rules.tar.gz https://www.snort.org/downloads/community/community-rules.tar.gz &&     mkdir -p /etc/snort/rules &&     tar zxvf /tmp/community-rules.tar.gz -C /etc/snort/rules --strip-components=1 &&     rm -f /tmp/community-rules.tar.gz &&     source /usr/local/rvm/scripts/rvm &&     source /etc/profile.d/rvm.sh &&     export PATH=$PATH:/usr/local/rvm/rubies/ruby-1.9.3-p551/bin &&     git clone git://github.com/Snorby/snorby.git /usr/local/src/snorby &&     sed -i "s/gem 'byebug'/gem 'pry-byebug', platform: [:ruby_20]/g" /usr/local/src/snorby/Gemfile &&     cd /usr/local/src/snorby &&     gem install --user-install executable-hooks bundler ; bundle install ; bundle update do_mysql ; bundle update dm-mysql-adapter' returned a non-zero code: 127

**Comment by schachr** [comment]
Fixed

**Comment by HenriWahl** [comment]
:+1
